version: '3'

services:
  mariadb:
    image: mariadb
    hostname: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mariadb_data

volumes:
  mariadb_data: